# Generated by Django 4.2.7 on 2023-11-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
