# Generated by Django 4.2.7 on 2023-11-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_contactus_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='currency_type',
        ),
    ]
