# Generated by Django 4.2.7 on 2023-11-26 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_source_alter_rate_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
