# Generated by Django 4.2.7 on 2023-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_rate_source_alter_rate_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email_from',
            field=models.EmailField(max_length=30, verbose_name='Email from'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.IntegerField(choices=[(1, 'Dollar'), (2, 'Euro'), (3, 'Bitcoin'), (4, 'Ethereum')], default=1, verbose_name='Currency type'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sell'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
